server:
  port: 8083

spring:
  datasource:
    generate-unique-name: false
    url: jdbc:postgresql://localhost:5432/blog
    username: spring
    password: security
#    name: blog
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
